version: "3"

services:
  caddy:
    image: abiosoft/caddy:latest
    ports:
      - "8080:8080" # port to proxy to flipt
    networks:
      - backend
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    environment:
      - HTTP_USERNAME=admin
      - HTTP_PASSWORD=password

  flipt:
    image: markphelps/flipt:latest
    # Note: no ports are exposed publicly as Caddy acts as a reverse proxy,
    # proxying all requests to 8080 to the Flipt container
    networks:
      - backend
networks:
  backend:
