version: "3"

services:
  dex:
    image: dexidp/dex:latest
    command: dex serve /etc/dex/config.yaml
    ports:
      - "5556:5556"
    volumes:
      - ./dex-config.yaml:/etc/dex/config.yaml
    networks:
      - flipt_network

  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/etc/flipt/config/default.yml
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    networks:
      - flipt_network

networks:
  flipt_network:
