version: "3"

services:
  caddy:
    image: caddy:latest
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    environment:
      - HTTP_USERNAME=admin
      - HTTP_PASSWORD_HASH=$$2a$$14$$aJbU.sSDUn0qCRmvpyjsxOdyt/a55NvI5d6u5xbNmZR.TYdlVskZi

  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    # Note: no ports are exposed publicly as Caddy acts as a reverse proxy,
    # proxying all requests to 8080 to the Flipt container
    depends_on: 
      - caddy
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    networks:
      - flipt_network

networks:
  flipt_network:
