# yaml-language-server: $schema=https://raw.githubusercontent.com/flipt-io/flipt/main/config/flipt.schema.json

# version: "1.0"
# log:
#   level: INFO
#   file:
#   encoding: console
#   grpc_level: ERROR

# ui:
#   enabled: true
#   default_theme: system

# cors:
#   enabled: false
#   allowed_origins: "*"

# cache:
#   enabled: false
#   backend: memory
#   ttl: 60s
#   redis:
#     host: localhost
#     port: 6379
#   memory:
#     eviction_interval: 5m # Evict Expired Items Every 5m

# server:
#   protocol: http
#   host: 0.0.0.0
#   https_port: 443
#   http_port: 8080
#   grpc_port: 9000

# db:
#   url: file:/var/opt/flipt/flipt.db
#   max_idle_conn: 2
#   max_open_conn: 0 # unlimited
#   conn_max_lifetime: 0 # unlimited

# tracing:
#   enabled: false
#   exporter: jaeger
#   jaeger:
#     host: localhost
#     port: 6831

# meta:
#   check_for_updates: true
