# log:
#   level: INFO

# ui:
#   enabled: true

# cache:
#   memory:
#     enabled: true

# server:
#   host: 0.0.0.0
#   http_port: 8080
#   grpc_port: 9000

# db:
#   url: sqlite3:///var/opt/flipt/flipt.db
#   migrations:
#     auto: true
#     path: /etc/flipt/config/migrations
