---
name: Validate Renovate Config
permissions:
  contents: read
on:
  push:
    paths:
      - ".github/renovate.json5"
  pull_request:
    paths:
      - ".github/renovate.json5"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Validate Renovate Config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.0.0
        with:
          validator_version: "41.91.1"
